### ISSUE TITLE
Get rid of server reset message

### ISSUE THREAD

**Issue by pietervanleeuwen** [Noterik/MuPoP#1]
In some cases, e.g. when a mobile device from a sleep reopens the message server reset is given. It's best to get rid of this message and to reload the page so the client reconnects directly instead of showing an unclear message.

**Comment by pietervanleeuwen** [comment]
Hi @scb2scb2,

Am I correct that this only means the connection was lost on the server with the screen, and a clientside reload would be a more userfriendly solution then the alert we now display?
If so we can modify eddie.js to do 

`window.location.reload(true); `

 instead of

 `alert('server reset');`

**Comment by scb2scb2** [comment]
I already prepared this and it was removed on my old code with a none blocking version. Will recheck what happend here.

**Comment by scb2scb2** [comment]
Fixed this in the new release of eddie/lou and is in testing on beta server
