### ISSUE TITLE
Geofence mobile application usage?

### ISSUE THREAD

**Issue by pietervanleeuwen** [Noterik/MuPoP#2]
Currently we allow anybody to join the mobile urls from any location in the world. In theory it's possible for users to do interactions from another location causing "ghost usage" on the mainscreen as there is then no clear user visible in front of the screens.

There are several solutions to this problem, with geofencing being the most straight forward solution. When opening the MuPoP mobile url this would ask the user to allow to use their geolocation, we can match this up against the coordinates of the Sound & Vision building to determine if the user is near the station or not.

**Comment by KellyMostert** [comment]
Hi Pieter,

I don't see any problems asking the user for the location, to eliminate the risk of this ghost usage possibility. Is the location stored in any way, or tied to other user information?

**Comment by pietervanleeuwen** [comment]
Ok, then we will go this route.

We didn't plan on storing any of this information, the sole purpose is to check whether the user is near the exhibition area or not.

**Comment by pietervanleeuwen** [comment]
We decided to take another approach as we don't know the accuracy of geofencing and also have to ask permission to the end user.
