### ISSUE TITLE
Recover in case of Tomcat is down

### ISSUE THREAD

**Issue by pietervanleeuwen** [Noterik/MuPoP#3]
During the Berlin conference and Cultuur in Beeld we experienced a couple of times a Tomcat outage (due to insufficient memory, machine will be upgraded). From this state the sticks currently cannot recover as an Apache page is shown that the proxy connection to Tomcat failed.

To fix this I propose the following two solutions:

1) Check on the server if Tomcat is running, if not start it again

2) If Apache detects the proxy connection failed send to a backup page that keeps checking instead of the current static page that does not recover anymore. This can be achieved by using a proxy balancer that gives priority to connect to Tomcat, but in case that fails falls back to a simple page that keeps reconnecting every X seconds. By means of this we recover once Tomcat is up again. See [this page](http://serverfault.com/questions/87507/fall-back-location-for-apaches-proxypass-directive) for a technical solution.

**Comment by scb2scb2** [comment]
I think we can do a 'whole' test in that lou now sends a servertime every 2seconds the current check now reacts only on the 200 http signal ill see if i can move that to a 'i got a time signal' instead. This way we should catch this one but also any other 'lou' problem since it demands a incoming time.

**Comment by pietervanleeuwen** [comment]
This will certainly help in a lot of cases, however there are cases that when a startup is performed while Tomcat is down the screen will not recover.
For this reason the in 2. proposed solution will work for any screen (both main and mobile) as long as Apache is up. But if Apache is down everything is down (as long as we don't do loadbalancing)

**Comment by scb2scb2** [comment]
First version implemented and tested on beta server. Lou/Eddie are updated now to support this

**Comment by pietervanleeuwen** [comment]
Great, 2 is then working now. 

We only need to add 1, but this is something we already use on our other cluster.

**Comment by pietervanleeuwen** [comment]
1. is now deployed on both beta and production. For 2. Lou needs to be updated on production and the apache config should be updated, right?

**Comment by scb2scb2** [comment]
That is correct it needs new Lou and Eddie (that will be deployed with lou).

**Comment by pietervanleeuwen** [comment]
Deployed on MuPoP production
