### ISSUE TITLE
Tekstaanpassingen in video app

### ISSUE THREAD

**Issue by KellyMostert** [Noterik/MuPoP#6]
Kan de volgende tekst aangepast worden?

Main screen:
- "Nederlandse mode in beeld"= **Raad het modetijdperk**
- "In Sound and Vision logo" = moet NL logo zijn, **in Beeld en Geluid:

![beeld-en-geluid_rood-rgb-e00034](https://cloud.githubusercontent.com/assets/24674263/21965037/ec2d2fb4-db57-11e6-9b9c-f160d8fdd153.png)

**

Smartphone:
- "Video gezien over" = vind deze tekst verwarrend, je zou het ook kunnen opvatten als "je hebt een video gezien over -onderwerp-. Liever "afspeelduur" oid.

**Comment by pietervanleeuwen** [comment]
Alles aangepast
